// Shared data model — mirrors the schemas in app-spec.md sections 4–7.

export type Task = {
  id: string;
  title: string;
  milestone: string; // e.g. "6 months to go"
  completed: boolean;
};

export type BudgetLine = {
  id: string;
  category: string;
  vendorName: string;
  quotedAmount: number;
  paidAmount: number;
};

export type Guest = {
  id: string;
  name: string;
  rsvpStatus: "confirmed" | "pending";
  dietaryTags: string[];
  tableId: string | null;
};

export type Table = {
  id: string;
  name: string;
  capacity: number;
  guestIds: string[];
};

export type WishlistCategory = {
  id: string;
  name: string;
  icon: string;
  locked: boolean;
  vendorIds: string[];
};

// Pro-only AI red/green flag review of a saved vendor. Generated by
// /api/review-vendor (see that route for the rubric), stored on the
// vendor once it comes back so it doesn't need to be re-run.
export type VendorReview = {
  flag: "green" | "red";
  headline: string;
  summary: string;
  sources: { title: string; url: string }[];
  reviewedAt: string; // ISO timestamp
};

export type Vendor = {
  id: string;
  categoryId: string;
  name: string;
  url: string;
  notes: string;
  reviewStatus: VendorReview | null;
};

export type Onboarding = {
  weddingDate: string | null; // ISO date
  totalBudget: number | null;
  guestCountEstimate: number | null;
};

export type TimelineEvent = {
  id: string;
  time: string; // "HH:MM", 24-hour, sorted on
  title: string;
  notes: string;
};

export type AppData = {
  unlocked: boolean;
  onboarded: boolean;
  proUnlocked: boolean;
  onboarding: Onboarding;
  tasks: Task[];
  budgetLines: BudgetLine[];
  guests: Guest[];
  tables: Table[];
  wishlistCategories: WishlistCategory[];
  vendors: Vendor[];
  timelineEvents: TimelineEvent[];
};

export const CATEGORY_OPTIONS = [
  "Venues",
  "Flowers",
  "Photo & video",
  "Catering",
  "Music",
  "Hair & makeup",
  "Celebrant",
  "Stationery",
  "Transport",
  "Other",
] as const;

export const SUGGESTED_MILESTONES = [
  "12–18 Months Before",
  "9–12 Months Before",
  "6–9 Months Before",
  "4–6 Months Before",
  "2–3 Months Before",
  "Final Month",
  "Final Week",
  "Wedding Day",
] as const;
